#!/usr/bin/env bash
# =============================================================================
# Aethera AI - One-shot Cloudflare Tunnel publisher (config-as-code mode)
# =============================================================================
# Wraps: cloudflared login -> tunnel create -> write config -> route DNS.
# Run this ON THE HOST where the Docker stack runs (not in the cloud sandbox).
#
#   bash infrastructure/cloudflare/publish.sh
#
# Reads CLOUDFLARE_TUNNEL_NAME and CLOUDFLARE_DOMAIN from .env (falling back to
# "aethera" / "ai.aetherahealthcare.com"). It does NOT create the Cloudflare
# Access login policy — cloudflared can't; do that in the dashboard or via the
# API (see step printed at the end and docs/PUBLISH.md).
# =============================================================================
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

# --- Load .env (non-fatal if missing) ---------------------------------------
if [[ -f .env ]]; then
  set -a; . ./.env; set +a
fi
TUNNEL_NAME="${CLOUDFLARE_TUNNEL_NAME:-aethera}"
DOMAIN="${CLOUDFLARE_DOMAIN:-ai.aetherahealthcare.com}"
CFG_DIR="${HOME}/.cloudflared"
CFG_FILE="${CLOUDFLARED_CONFIG:-${CFG_DIR}/config.yml}"

echo ">> Publishing tunnel '${TUNNEL_NAME}' for ${DOMAIN}"

# --- 1. cloudflared present? -------------------------------------------------
if ! command -v cloudflared >/dev/null 2>&1; then
  cat <<'EOF'
ERROR: cloudflared is not installed.
  macOS:   brew install cloudflared
  Linux:   https://pkg.cloudflare.com/  (or download the binary from
           https://github.com/cloudflare/cloudflared/releases/latest)
  Windows: winget install --id Cloudflare.cloudflared  (or use tunnel_setup.ps1)
EOF
  exit 1
fi

# --- 2. Authenticate (browser) once ------------------------------------------
if [[ ! -f "${CFG_DIR}/cert.pem" ]]; then
  echo ">> Logging in to Cloudflare (a browser window will open)..."
  cloudflared tunnel login
else
  echo ">> Already authenticated (${CFG_DIR}/cert.pem present)."
fi

# --- 3. Create the tunnel if it doesn't exist --------------------------------
get_uuid() {
  cloudflared tunnel list --output json 2>/dev/null \
    | python3 -c "import sys,json;
data=json.load(sys.stdin)
print(next((t['id'] for t in data if t.get('name')=='${TUNNEL_NAME}'), ''))" 2>/dev/null
}

UUID="$(get_uuid || true)"
if [[ -z "${UUID}" ]]; then
  echo ">> Creating tunnel '${TUNNEL_NAME}'..."
  cloudflared tunnel create "${TUNNEL_NAME}"
  UUID="$(get_uuid || true)"
else
  echo ">> Tunnel '${TUNNEL_NAME}' already exists (${UUID})."
fi

if [[ -z "${UUID}" ]]; then
  echo "ERROR: could not determine tunnel UUID. Run 'cloudflared tunnel list' to inspect."
  exit 1
fi

CRED_FILE="${CFG_DIR}/${UUID}.json"
if [[ ! -f "${CRED_FILE}" ]]; then
  echo "WARNING: credentials file ${CRED_FILE} not found; check ${CFG_DIR}."
fi

# --- 4. Write the ingress config (single-domain, path-routed) ----------------
echo ">> Writing ${CFG_FILE}"
mkdir -p "$(dirname "${CFG_FILE}")"
cat > "${CFG_FILE}" <<EOF
# Generated by infrastructure/cloudflare/publish.sh
tunnel: ${UUID}
credentials-file: ${CRED_FILE}

ingress:
  - hostname: ${DOMAIN}
    path: ^/api/.*
    service: http://localhost:8000
    originRequest:
      noTLSVerify: true
  - hostname: ${DOMAIN}
    path: ^/ws.*
    service: http://localhost:8000
    originRequest:
      noTLSVerify: true
  - hostname: ${DOMAIN}
    service: http://localhost:3000
    originRequest:
      noTLSVerify: true
  - service: http_status:404
EOF

# --- 5. Route DNS to the tunnel ---------------------------------------------
echo ">> Routing DNS ${DOMAIN} -> tunnel ${TUNNEL_NAME}"
cloudflared tunnel route dns "${TUNNEL_NAME}" "${DOMAIN}" || \
  echo "   (DNS route may already exist — continuing.)"

# --- 6. Done -----------------------------------------------------------------
cat <<EOF

Tunnel is configured. Next:

  1) REQUIRE LOGIN (Cloudflare Access) — cloudflared cannot do this; in the
     dashboard go to Zero Trust > Access > Applications > Add (Self-hosted):
       Application domain: ${DOMAIN}
       Policy: Allow, Include > Emails = ${CLOUDFLARE_ACCESS_EMAIL:-<your-email>}
     (Template: infrastructure/cloudflare/access_policy.json)

  2) START the tunnel:
       cloudflared tunnel run ${TUNNEL_NAME}
     or install it as a background service:
       sudo cloudflared service install
       sudo cloudflared tunnel run ${TUNNEL_NAME}

  3) Make sure the app stack is up (UI on :3000, API on :8000):
       docker compose up -d
     and that the UI was built with VITE_API_URL=https://${DOMAIN}

Then visit https://${DOMAIN} — you'll get the Access login before the app loads.
EOF
